name: Test Action

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          use-auto-merge: true
          allowed-actors: tjenkinson, dependabot[bot]
          package-block-list: '@actions/core, @actions/github'
